### ISSUE TITLE
Testado no GLPI 10.0.0

### ISSUE THREAD

**Issue by zuqueto** [stifdrp/glpi-uspoauth#9]
testado com o glpi 10 porem muda um pouco a forma de instalar. apos fazer a instalação como na versão 9.5 descompacte os arquivos do link https://missouri.fo.usp.br/glpi-agent/glpi10.rar e submeta a pasta do glpi apos o upgrade para a versão 10.0.0

**Comment by tadeumesquita** [comment]
Fechado e movido para as discussões.
https://github.com/stifdrp/glpi-uspoauth/discussions/12
